using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealCashMs.Models;

// Backend model for cooks records.
public class Cook{
    // change this Employee key into a no autogenerated key, later so that,
    // I'd design a specific algorithm for generating the Employee's no.
    // whatever will be displayed as the employee no, will simply be an abstraction of
    // the employee no and will definitely be very different from what is generated
    //such that no hacker can forge the employee no.
    // whatever employee no is generated should have the ability to change after each day.
    // so that in case a hacker learns the algorithm by today, by tommorow it woulld have changed.
    [Key]
    public string CookNo{get;set;} = null!;// Keyname must be different from the one it has a relationship with.

    public bool onDuty{get;set;}
    // adding the one to one relationship between the Cook and the Employees table.
    // note that here I have'nt added a foreign key directly.
    // It definitely knows that this is a one to one relationship.
    // simply ensure the name of the keys in both tables defer even if they reffer to the same data type
    public string EmployeeNo{get;set;} = null!;

    [ForeignKey("EmployeeNo")]
    public virtual Employee employeesTable{get;set;} = null!;
    //the foreign key and the navigation Class.
    // removed this temporarily cause it was causing some errors.
    public int dayOfTheYear{get;set;}
    public MealsADay mealCooked{get;set;} = null!;
}