using System.ComponentModel.DataAnnotations;

namespace RealCashMs.Models;

// If you need to add some new food, then you'll defiinitely first of all add it to
// the enum of the mealCodes.
public enum mealCodes{
    Chapati,Mandazi,Githeri
}

public class Meal{
    // This key is autogenerated by the entity framework.
    // If you dont want the entity framework core to generate values for you use,     [DatabaseGenerated(DatabaseGeneratedOption.None)]
    //[DatabaseGenerated(DatabaseGeneratedOption.None)]
    //public int mealIdentifier{get;set;} // this can't be the code to identify the meal.
    [Key]
    public mealCodes mealName{get;set;}
    public int mealPrice{get;set;}

    // The quantity of food remaining.That can be accessed each time a new instance of the meal is accessed.
    public int quantityRemaining{get;set;} // should be decremented each time the food is requested.

    // To declare the many to one relationship with the customer.
    // This is the foreign key. am using the exact same name as that in the Customer
    // table to avoid using the ForeignKey attribute which associates a different name with that on the customer table.
    public string receiptNo{get;set;} = null!; // I've tried making the foreign keys nullable. Cause for the meal table the foreign key isnt a must
    public virtual Customer customerInstance{get;set;} = null!;

    // Foreign key for the MealsADay
    // below is the mealsADay class.
    public int dayOfTheYear{get;set;}
    public virtual MealsADay mealsOftheDay{get;set;} = null!;
}